@echo off
echo Starting PDF Parser Service...
echo.
echo Checking Python installation...
python --version
echo.
echo Installing required packages...
pip install -r requirements.txt
echo.
echo Downloading spaCy language model...
python -m spacy download en_core_web_sm
echo.
echo Starting Flask server on port 5001...
python main.py
